[modules]
autoload = no
load = res_pjproject.so
load = res_sorcery_astdb.so
load = res_sorcery_config.so
load = res_sorcery_memory.so
load = res_pjsip.so
load = res_pjsip_authenticator_digest.so
load = res_pjsip_endpoint_identifier_user.so
load = res_pjsip_registrar.so
load = res_pjsip_pubsub.so
load = res_pjsip_session.so
load = res_rtp_asterisk.so
load = res_pjsip_sdp_rtp.so
load = chan_pjsip.so
load = res_http_websocket.so
load = res_websocket_client.so
load = res_stasis.so
load = res_stasis_answer.so
load = res_stasis_device_state.so
load = res_stasis_playback.so
load = res_stasis_recording.so
load = res_stasis_snoop.so
load = res_ari_model.so
load = res_ari.so
load = res_ari_asterisk.so
load = res_ari_channels.so
load = pbx_config.so
load = app_playback.so
load = res_audiosocket.so
load = app_audiosocket.so
load = func_uuid.so
load = func_global.so
load = format_wav.so
load = codec_ulaw.so
load = codec_alaw.so
load = codec_resample.so
